language: java

script: ./bin/build.sh clean test

cache:
  directories:
    - $HOME/.m2/repository

matrix:
  include:
    - jdk: oraclejdk8
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "chmod +x ./bin/build.sh"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx128m"
    - jdk: oraclejdk7
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "chmod +x ./bin/build.sh"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx128m"
    - jdk: openjdk8
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "chmod +x ./bin/build.sh"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx128m"
    - jdk: openjdk7
      dist: trusty
      group: edge
      sudo: required
      before_script:
        - "chmod +x ./bin/build.sh"
        - "echo $JAVA_OPTS"
        - "export JAVA_OPTS=-Xmx128m"